# Annual Data

In [3]:
import pandas as pd

In [ ]:
df = pd.read_csv('../data/intermediate/annual.csv')
df = df.drop(columns=["Unnamed: 0"])

,Region,year,total,drafted,pmc,volunteers,prisoners,contract,slavic,non_slavic,...,disability_per10k,uneployment,median_income,consumption,av_income,share_poverty,% Russians,% Slavs,Excessive Marriages,ex_nup_per100k
0,Алтайский край,2022,400,0,14,33,8,291,376,24,...,63.2,3.7,24037.0,25062.0,31145.0,15.4,95.45,96.08,2007.6,430.387834
1,Алтайский край,2023,677,80,40,120,218,51,631,46,...,NaN,NaN,NaN,NaN,NaN,NaN,95.45,96.08,2007.6,430.387834
2,Алтайский край,2024,985,91,0,425,62,137,921,64,...,NaN,NaN,NaN,NaN,NaN,NaN,95.45,96.08,2007.6,430.387834
3,Алтайский край,2025,30,0,0,28,0,2,28,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2007.6,430.387834
4,Амурская область,2022,100,0,5,25,0,67,91,9,...,39.5,4.2,34565.7,35974.0,44900.0,13.3,95.17,95.95,1890.4,1007.471834
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
340,Ямало-Ненецкий автономный округ,2025,38,6,0,15,0,1,26,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
341,Ярославская область,2022,71,0,0,14,36,21,68,3,...,40.5,5.0,30524.1,30810.0,38060.0,8.8,96.52,97.04,780.0,293.731100
342,Ярославская область,2023,194,59,8,44,46,10,190,4,...,NaN,NaN,NaN,NaN,NaN,NaN,96.52,97.04,780.0,293.731100
343,Ярославская область,2024,230,25,5,89,0,35,222,8,...,NaN,NaN,NaN,NaN,NaN,NaN,96.52,97.04,780.0,293.731100
344,Ярославская область,2025,13,0,0,0,0,1,12,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,780.0,293.731100

# Over-representation

In [9]:
df['share_slav_casualties'] = df["slavic"]/df['total']*100
df['ethnic_bias'] = df["share_slav_casualties"] - df['% Slavs']

In [11]:
df

,Region,year,total,drafted,pmc,volunteers,prisoners,contract,slavic,non_slavic,...,median_income,consumption,av_income,share_poverty,% Russians,% Slavs,Excessive Marriages,ex_nup_per100k,share_slav_casualties,ethnic_bias
0,Алтайский край,2022,400,0,14,33,8,291,376,24,...,24037.0,25062.0,31145.0,15.4,95.45,96.08,2007.6,430.387834,94.000000,-2.080000
1,Алтайский край,2023,677,80,40,120,218,51,631,46,...,NaN,NaN,NaN,NaN,95.45,96.08,2007.6,430.387834,93.205318,-2.874682
2,Алтайский край,2024,985,91,0,425,62,137,921,64,...,NaN,NaN,NaN,NaN,95.45,96.08,2007.6,430.387834,93.502538,-2.577462
3,Алтайский край,2025,30,0,0,28,0,2,28,2,...,NaN,NaN,NaN,NaN,NaN,NaN,2007.6,430.387834,93.333333,NaN
4,Амурская область,2022,100,0,5,25,0,67,91,9,...,34565.7,35974.0,44900.0,13.3,95.17,95.95,1890.4,1007.471834,91.000000,-4.950000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
340,Ямало-Ненецкий автономный округ,2025,38,6,0,15,0,1,26,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,68.421053,NaN
341,Ярославская область,2022,71,0,0,14,36,21,68,3,...,30524.1,30810.0,38060.0,8.8,96.52,97.04,780.0,293.731100,95.774648,-1.265352
342,Ярославская область,2023,194,59,8,44,46,10,190,4,...,NaN,NaN,NaN,NaN,96.52,97.04,780.0,293.731100,97.938144,0.898144
343,Ярославская область,2024,230,25,5,89,0,35,222,8,...,NaN,NaN,NaN,NaN,96.52,97.04,780.0,293.731100,96.521739,-0.518261
344,Ярославская область,2025,13,0,0,0,0,1,12,1,...,NaN,NaN,NaN,NaN,NaN,NaN,780.0,293.731100,92.307692,NaN